config/routes.rb
NewAuthDemo::Application.routes.draw do

  get 'static_pages/home'
  get 'static_pages/contact'
  get 'static_pages/about'
  get 'static_pages/help'


  resources :users, :only => [:create, :new, :show]
  resource :session, :only => [:create, :destroy, :new]

  root :to => "users#show"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :password_digest, :presence => true
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true, :uniqueness => true
  validates :username, :presence => true, :uniqueness => true

  before_validation :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    user.try(:is_password?, password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(unencrypted_password)
    BCrypt::Password.new(self.password_digest).is_password?(unencrypted_password)
  end

  def password=(unencrypted_password)
    if unencrypted_password.present?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # Expose these methods to the views
  helper_method :current_user, :signed_in?

  private

  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:token] = user.reset_session_token!
  end

  def sign_out
    current_user.try(:reset_session_token!)
    session[:token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end

  def require_signed_out!
    redirect_to user_url(current_user) if signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_signed_out!, :only => [:new, :create]
  before_action :require_signed_in!, :only => [:destroy]

  def new
  end

  def create
    @user = User.find_by_credentials(
      user_params[:username],
      user_params[:password]
    )

    if @user
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signed_in!, :only => [:show]
  before_action :require_signed_out!, :only => [:create, :new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="../../assets/stylesheets/bootstrap.css" type="text/css" media="screen" title="no title" charset="utf-8">

  <%= csrf_meta_tags %>
  <title>NewAuthDemo</title>
  <style> ul{margin: 0; padding: 0;list-style:none;}</style>
</head>
<body data-spy="scroll" data-target=".sidebar">

  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" >
          <span class="sr-only">Toggle testing</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">OUR AWESOME APP!</a>
      </div>
      <div class="navbar-collapse collapse" style="height: 1px" id="navbar-collapse">
        <ul class="navbar-nav nav">
          <li class="active"><a href="<%= static_pages_home_url %>">Home</a></li>
          <li ><a href="<%= static_pages_contact_url %>" >Contact</a></li>
          <li ><a href="<%= static_pages_about_url %>">About</a></li>
          <li ><a href="<%= static_pages_help_url %>">Help</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              AWESOME DROPDOWN WUT
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li ><a href="#" >One</a></li>
              <li class="divider"></li>
              <li ><a href="#">Two</a></li>
              <li class="divider"></li>
              <li ><a href="#" >3</a></li>
            </ul>
          </li>

        </ul>
      </div>

    </div>


  </nav>



  <!--    <nav class="navbar-default nav" >
  <div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
  <span class="sr-only">Toggle navigation</span>
  <span class="icon-bar"></span>
  </button>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav-pills nav">
  <li class="active"><a href="#">Home</a></li>
  <li ><a href="#" >Away</a></li>
  <li ><a href="#">From</a></li>
  <li ><a href="#">Home</a></li>
  </ul>
  </div>
  </div>
  </nav> -->

  <br>
  <br>
  <div class="container">
    <% if signed_in? %>
    <ul>
      <li>Signed in as: <%= current_user.username %></li>
      <li><%= button_to "Sign Out", session_url, :method => :delete %></li>
    </ul>
    <% else %>
    <p>
      <%= link_to "Sign In", new_session_url %> or
      <%= link_to "Sign up", new_user_url %>
    </p>
    <% end %>

    <hr>

    <% if flash[:errors] %>
    <h3>Please fix the following errors:</h3>
    <ul>
      <% flash[:errors].each do |error| %>
      <li><%= error %></li>
      <% end %>
    </ul>
    <% end %>
  </div>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/static_pages/about.html.erb
<div class="jumbotron">
  <h1>About us</h1>
  <div class="row">
    <div class="col-xs-6">
      <h2>stuff</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p></div>
    <div class="col-xs-6">
      <h2>more stuff</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p></div>
  </div>

</div>

<div class="row text-center" >
  <h1>content</h1>
  <div class="col-xs-3">
    <img width="100%" class="img-circle" src="http://i.imgur.com/I1mdz61.png">
    <h2>Nick</h2>
    <p>Nicolas Kim Coppola (born January 7, 1964),[1][2][3][4] known professionally as Nicolas Cage, is an American actor and filmmaker. He has performed in leading roles in a variety of films, ranging from romantic comedies and dramas to science fiction and action films. Cage is known for his prolificacy, appearing in at least one film per year nearly every year since 1980, with the exception of 1985 and 1991.</p>
  </div>
  <div class="col-xs-3">
    <img width="100%" class="img-circle" src="http://i.imgur.com/Yg527xC.png">
    <h2>NCage</h2>
    <p>Cage received an Academy Award, a Golden Globe, and Screen Actors Guild Award for his performance as an alcoholic Hollywood writer in Leaving Las Vegas (1995) before coming to the attention of wider audiences with mainstream films such as The Rock (1996), Face/Off (1997), Con Air (1997), City of Angels (1998), and National Treasure (2004). He earned his second Academy Award nomination for his performance as Charlie and Donald Kaufman in Adaptation (2002). In 2002, he directed the film Sonny, for which he was nominated for Grand Special Prize at Deauville Film Festival. Cage owns the production company Saturn Films and has produced films such as Shadow of the Vampire (2000) and The Life of David Gale (2003).</p>
  </div>
  <div class="col-xs-3">
    <img width="100%" class="img-circle"  src="http://i.imgur.com/RL7dLYa.jpg">
    <h2>OTG</h2>
    <p>Cage's acting has been praised by influential film critic Roger Ebert, who wrote in his "Great Movies" essay, about the film Adaptation, that: "There are often lists of the great living male movie stars: De Niro, Nicholson and Pacino, usually. How often do you see the name of Nicolas Cage? He should always be up there. He's daring and fearless in his choice of roles, and unafraid to crawl out on a limb, saw it off and remain suspended in air. No one else can project inner trembling so effectively... he always seems so earnest. However improbable his character, he never winks at the audience. He is committed to the character with every atom and plays him as if he were him."[55] In response to mixed reviews of Knowing and their focus on criticizing Cage, Ebert defended both Cage as an actor and the film which (in contrast to other critics) he gave four out of four stars.[56]</p>
  </div>
  <div class="col-xs-3">
    <img width="100%" class="img-circle" src="http://i.imgur.com/LpI9lmW.jpg">
    <h2>Cage Nick</h2>
    <p>Since his minor role in the film Fast Times at Ridgemont High, with Sean Penn, Cage has appeared in a wide range of films, both mainstream and offbeat.[16] He auditioned for the role of Dallas Winston in his uncle's film The Outsiders, based on S.E. Hinton's novel, but lost to Matt Dillon.[17] He was also in Coppola's films Rumble Fish[18] and Peggy Sue Got Married.[19]</p>
  </div>
</div>

app/views/static_pages/contact.html.erb
<h1>StaticPages#Contact</h1>

<div class="row">

  <div class="col-xs-6">
    <table class="table table-striped">
      <tr>
        <th>Name</th>
        <th>Phone</th>
      </tr>
      <tr>
        <td>Bob</td>
        <td>123-456-7890</td>
      </tr>
      <tr>
        <td>Cindy</td>
        <td>789-456-1230</td>
      </tr>
    </table>
    <h1>got back</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <h1>status of order?</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
  <div class="col-xs-6">
    <div class="fake-flash" ></div>
    <h1>Contact</h1>
    <form role="form" id="contact-form">
      <div class="form-group">
        <label for="personal_information">Personal Information</label>
        <input type="text"
        name="personal_information"
        value=""
        id="personal_information"
        class="form-control">
      </div>


      <div class="form-group">
        <label for="email_address">Email Address</label>
        <input type="text"
         name="email_address"
         value=""
         id="email_address"
         class="form-control">
      </div>



      <label for="general">Question/Comment</label>
      <div class="form-group">
        <textarea
        placeholder="general question or comment?"
        class="form-control"
        id="general"></textarea>
      </div>

      <button class="submit">Submit</button>
    </form>
  </div>

</div>

<script>

$(function(){

  // window.boundEvent();

    $('form').on('submit',  function (event) {
      event.preventDefault();
      $('.fake-flash').empty();
      $('input').removeClass("alert-danger alert-success");

      $('input').each( function ($i) {

        if ( $(this).val()=== "") {
           $(this).addClass('alert-danger');
        }else {
           $(this).addClass('alert-success');
        }
      })

      if ($('.alert-danger').length === 0) {
        // alert("all inputs are provided")
        $('.fake-flash').html('All inputs are provided!');
      }else{
        $('.fake-flash').html('You forget an input!');
      }
    })



}());

</script>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form class="form-inline" role="form" action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

 <div class="form-group">
   <label for="user_username">Username</label>
   <input
      id="user_username"
      name="user[username]"
      type="text"
      class="form-control"
      placeholder="Enter Username Here">
 </div>

<div class="form-group">
  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password"
     class="form-control"
     placeholder="Put Your Password Here Genius">
</div>



  <input type="submit" class="btn btn-default" value="<%= message %>">
</form>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<p>Hello, dear user!</p>